# Generated by Django 3.2.25 on 2024-07-30 10:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery', '0017_auto_20220422_1912'),
    ]

    operations = [
        # Rename Fields
        migrations.RenameField(
            model_name='LightGallery',
            old_name='zoomActualSize',
            new_name='actualSize',
        ),
        migrations.RenameField(
            model_name='LightGallery',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='LightGallery',
            old_name='currentPagerPosition',
            new_name='alignThumbnails',
        ),
        migrations.RenameField(
            model_name='LightGallery',
            old_name='thumbContHeight',
            new_name='thumbHeight',
        ),

        # Remove Fields
        migrations.RemoveField(
            model_name='LightGallery',
            name='pullCaptionUp',
        ),
        migrations.RemoveField(
            model_name='LightGallery',
            name='easing',
        ),
        migrations.RemoveField(
            model_name='LightGallery',
            name='useLeft',
        ),
        migrations.RemoveField(
            model_name='LightGallery',
            name='showAfterLoad',
        ),
        migrations.RemoveField(
            model_name='LightGallery',
            name='googlePlus',
        ),
        migrations.RemoveField(
            model_name='LightGallery',
            name='googlePlusDropdownText',
        ),

        # Add Fields (Alphabetical order for clarity within this block)
        migrations.AddField(
            model_name='LightGallery',
            name='allowMediaOverlap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='appendAutoplayControlsTo',
            field=models.CharField(default='.lg-toolbar', help_text='Specify where the autoplay controls should be appended.', max_length=50),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='appendSubHtmlTo',
            field=models.CharField(default='.lg-sub-html', max_length=50),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='appendThumbnailsTo',
            field=models.CharField(default='.lg-components', help_text='Control where the thumbnails should be appended.', max_length=50),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='autoplay',
            field=models.BooleanField(default=True, help_text='Enable autoplay plugin.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='autoplayControls',
            field=models.BooleanField(default=True, help_text='Show/hide autoplay controls.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='closeOnTap',
            field=models.BooleanField(default=True, help_text='Allows clicks on black area to close gallery.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='defaultCaptionHeight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='flipHorizontal',
            field=models.BooleanField(default=True, help_text='Enable flip horizontal button.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='flipVertical',
            field=models.BooleanField(default=True, help_text='Enable flip vertical button.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='forceSlideShowAutoplay',
            field=models.BooleanField(default=False, help_text='If false autoplay will be stopped after first user action.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='getCaptionFromTitleOrAlt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='hideScrollbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='iframeHeight',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='iframeMaxHeight',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='iframeWidth',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='infiniteZoom',
            field=models.BooleanField(default=True, help_text='Enable/Disable infinite zoom for zoom plugin.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='licenseKey',
            field=models.CharField(blank=True, default='0000-0000-000-0000', max_length=30),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='loadYouTubePoster',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='loadYouTubeThumbnail',
            field=models.BooleanField(default=True, help_text='Automatically load thumbnails for YouTube videos (thumbnail plugin).'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='mobileControls',
            field=models.BooleanField(default=False, help_text='Enable controls on mobile devices.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='mobileDownload',
            field=models.BooleanField(default=False, help_text='Enable download button on mobile devices.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='mobileShowCloseIcon',
            field=models.BooleanField(default=False, help_text='Show close icon on mobile devices.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='numberOfSlideItemsInDom',
            field=models.PositiveIntegerField(default=10, help_text='Control how many slide items should be kept in dom at a time (min 3).'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='progressBar',
            field=models.BooleanField(default=True, help_text='Show autoplay progress bar.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='resetScrollPosition',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='rotate',
            field=models.BooleanField(default=True, help_text='Enable/Disable rotate plugin.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='rotateLeft',
            field=models.BooleanField(default=True, help_text='Enable rotate left button.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='rotateRight',
            field=models.BooleanField(default=True, help_text='Enable rotate right button.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='rotateSpeed',
            field=models.PositiveIntegerField(default=400, help_text='Rotate speed in milliseconds.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='showBarsAfter',
            field=models.PositiveIntegerField(default=10000, help_text='Delay in hiding controls for the first time when gallery is opened.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='showCloseIcon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='showMaximizeIcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='showZoomInOutIcons',
            field=models.BooleanField(default=False, help_text='Show zoom in, zoom out icons for zoom plugin.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='slideDelay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='slideShowAutoplay',
            field=models.BooleanField(default=False, help_text='Enable slideshow autoplay.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='slideShowInterval',
            field=models.PositiveIntegerField(default=5000, help_text='Time (in ms) between each auto transition for slideshow.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='startAnimationDuration',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='subHtmlSelectorRelative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='swipeToClose',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='thumbnailSwipeThreshold',
            field=models.PositiveIntegerField(default=10, help_text='Swipe threshold for thumbnails.'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='trapFocus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='videoMaxSize',
            field=models.CharField(default='1280-720', max_length=20),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='youTubeThumbSize',
            field=models.PositiveIntegerField(default=1, help_text='YouTube thumbnail size (thumbnail plugin).'),
        ),
        migrations.AddField(
            model_name='LightGallery',
            name='zoomFromOrigin',
            field=models.BooleanField(default=True),
        ),

        # Alter Fields
        migrations.AlterField(
            model_name='LightGallery',
            name='speed',
            field=models.PositiveIntegerField(default=400, help_text='Transition duration (in ms)'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='backdropDuration',
            field=models.PositiveIntegerField(default=300, help_text='Lightgallery backdrop transtion duration. Do not change the value of backdrop via css'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='hideBarsDelay',
            field=models.PositiveIntegerField(default=0, help_text="Delay for hiding gallery controls in ms. Pass 0 if you don't want to hide the controls."),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='preload',
            field=models.PositiveIntegerField(default=2, help_text='Number of preload slides. will execute only after the current slide is fully loaded'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='alignThumbnails',
            field=models.CharField(choices=[['left', 'Left'], ['middle', 'Middle'], ['right', 'Right']], default='middle', help_text="Position of thumbnails when the width of all thumbnails combined is less than the gallery's width.", max_length=255),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='thumbHeight',
            field=models.CharField(default='80px', help_text='Height of each thumbnails.', max_length=20), # Max length was 255, changed to 20
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='toggleThumb',
            field=models.BooleanField(default=False, help_text='Enable toggle captions and thumbnails button.'), # Help text updated
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='zoomScale', # Assuming this is the correct field name for the 'scale' setting in zoom plugin
            field=models.FloatField(default=1, help_text='Value of zoom should be incremented/decremented'),
        ),
         migrations.AlterField(
            model_name='LightGallery',
            name='galleryId',
            field=models.CharField(default='1', help_text='Unique id for each gallery. It is mandatory when you use hash plugin for multiple galleries on the same page', max_length=255),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='zoomEnableZoomAfter',
            field=models.PositiveIntegerField(default=300, help_text='Number in ms'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='mousewheel',
            field=models.BooleanField(default=False, help_text='Change slide on mousewheel'),
        ),
        migrations.AlterField(
            model_name='LightGallery', # For existing swipeThreshold field which is now core
            name='swipeThreshold',
            field=models.PositiveIntegerField(default=50, help_text='By setting the swipeThreshold (in px) you can set how far the user must swipe for the next/prev image'),
        ),
         migrations.AlterField(
            model_name='LightGallery',
            name='zoom', # Default changed
            field=models.BooleanField(default=True, help_text='Enable/Disable zoom plugin'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='fullscreen', # Default changed
            field=models.BooleanField(default=True, help_text='Enable/Disable fullscreen plugin'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='pager', # Default changed
            field=models.BooleanField(default=True, help_text='Enable/disable pager for this gallery'),
        ),
        migrations.AlterField(
            model_name='LightGallery',
            name='hash', # Default changed
            field=models.BooleanField(default=True, help_text='Enable/Disable hash plugin'),
        ),
    ]
